"use client";

import React, { useState } from "react";
import { ChatMessages } from "@/app/dashboard/components/chat-messages";
import { ChatInput } from "@/app/dashboard/components/chat-input";

// Message type for the chat
interface Message {
  role: "user" | "bot";
  content: string;
}

export function Chat() {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: "bot",
      content: "Hello! I'm your medical assistant. How can I help you today?",
    },
  ]);
  const [inputMessage, setInputMessage] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  // Function to handle sending a message
  async function handleSendMessage(e: React.FormEvent) {
    e.preventDefault();
    
    if (!inputMessage.trim() || isLoading) return;

    const userMessage: Message = {
      role: "user",
      content: inputMessage,
    };

    // Add the user message to the chat
    setMessages((prev) => [...prev, userMessage]);
    setInputMessage("");
    setIsLoading(true);

    // In a real app, you would call your AI service here
    // This is a simple mock response
    setTimeout(() => {
      const botMessage: Message = {
        role: "bot",
        content: "This is a mock response. In a real application, this would be generated by an AI model based on your medical query.",
      };
      setMessages((prev) => [...prev, botMessage]);
      setIsLoading(false);
    }, 1000);
  }

  return (
    <div className="bg-gray-50 flex-1">
      <main className="mx-auto flex flex-col h-[calc(100vh-4rem)] max-w-4xl p-4">
        {/* Chat messages component */}
        <ChatMessages messages={messages} isLoading={isLoading} />

        {/* Chat input component */}
        <ChatInput 
          inputMessage={inputMessage}
          setInputMessage={setInputMessage}
          handleSendMessage={handleSendMessage}
          isLoading={isLoading}
        />
      </main>
    </div>
  );
}
