"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { Message, Thread } from "@/types/chat";
import { v4 as uuidv4 } from "uuid"; // You'll need to install this package

interface ChatContextType {
  threads: Thread[];
  activeThreadId: string | null;
  createThread: (name: string) => string; // Returns the thread ID
  deleteThread: (threadId: string) => void;
  sendMessage: (content: string) => void;
  selectThread: (threadId: string) => void;
  renameThread: (threadId: string, newName: string) => void;
  activeThread: Thread | null;
  isLoading: boolean;
}

const ChatContext = createContext<ChatContextType | undefined>(undefined);

export function ChatProvider({ children }: { children: React.ReactNode }) {
  const [threads, setThreads] = useState<Thread[]>([]);
  const [activeThreadId, setActiveThreadId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  // On first load, try to get threads from local storage
  useEffect(() => {
    const savedThreads = localStorage.getItem("chatThreads");
    if (savedThreads) {
      try {
        const parsedThreads = JSON.parse(savedThreads, (key, value) => {
          if (key === "createdAt" || key === "updatedAt" || key === "timestamp") {
            return new Date(value);
          }
          return value;
        });
        setThreads(parsedThreads);
        
        // Set the most recent thread as active if it exists
        if (parsedThreads.length > 0) {
          setActiveThreadId(parsedThreads[0].id);
        }
      } catch (error) {
        console.error("Failed to load chat threads:", error);
      }
    }
  }, []);

  // Save threads to local storage whenever they change
  useEffect(() => {
    if (threads.length > 0) {
      localStorage.setItem("chatThreads", JSON.stringify(threads));
    }
  }, [threads]);

  const activeThread = activeThreadId 
    ? threads.find(thread => thread.id === activeThreadId) || null
    : null;

  const createThread = (name: string) => {
    const newThread: Thread = {
      id: uuidv4(),
      name,
      messages: [{
        id: uuidv4(),
        role: "bot",
        content: "Xin chào! Tôi là phụ tá AI thông minh của bạn đây. Xem tôi có thể giúp gì được nào?",
        timestamp: new Date()
      }],
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: "current-user-id" // In a real app, get this from authentication
    };

    setThreads(prevThreads => [newThread, ...prevThreads]);
    setActiveThreadId(newThread.id);
    return newThread.id;
  };

  const deleteThread = (threadId: string) => {
    setThreads(prevThreads => prevThreads.filter(thread => thread.id !== threadId));
    
    if (activeThreadId === threadId) {
      // Set the next thread as active, or null if no threads left
      setActiveThreadId(threads.length > 1 ? threads[0].id : null);
    }
  };

  const sendMessage = async (content: string) => {
    if (!activeThreadId || !content.trim() || isLoading) return;

    const userMessageId = uuidv4();
    const userMessage: Message = {
      id: userMessageId,
      role: "user",
      content: content.trim(),
      timestamp: new Date()
    };

    // Update the thread with the user message
    setThreads(prevThreads => 
      prevThreads.map(thread => 
        thread.id === activeThreadId 
          ? {
              ...thread,
              messages: [...thread.messages, userMessage],
              updatedAt: new Date()
            }
          : thread
      )
    );

    setIsLoading(true);

    // In a real app, call your AI service here
    // Simulating a delay for the bot response
    setTimeout(() => {
      const botMessage: Message = {
        id: uuidv4(),
        role: "bot",
        content: "This is a mock response. In a real application, this would be generated by an AI model based on your medical query.",
        timestamp: new Date()
      };

      // Update the thread with the bot message
      setThreads(prevThreads => 
        prevThreads.map(thread => 
          thread.id === activeThreadId 
            ? {
                ...thread,
                messages: [...thread.messages, botMessage],
                updatedAt: new Date()
              }
            : thread
        )
      );
      
      setIsLoading(false);
    }, 1000);
  };

  const selectThread = (threadId: string) => {
    setActiveThreadId(threadId);
  };

  const renameThread = (threadId: string, newName: string) => {
    if (!newName.trim()) return;

    setThreads(prevThreads => 
      prevThreads.map(thread => 
        thread.id === threadId 
          ? { ...thread, name: newName.trim() }
          : thread
      )
    );
  };

  return (
    <ChatContext.Provider value={{
      threads,
      activeThreadId,
      createThread,
      deleteThread,
      sendMessage,
      selectThread,
      renameThread,
      activeThread,
      isLoading
    }}>
      {children}
    </ChatContext.Provider>
  );
}

export function useChat() {
  const context = useContext(ChatContext);
  if (context === undefined) {
    throw new Error("useChat must be used within a ChatProvider");
  }
  return context;
}
