"use client";

import { useSession } from "next-auth/react";
import { redirect } from "next/navigation";
import { useState } from "react";
import { signOut } from "next-auth/react";

// Message type for the chat
interface Message {
  role: "user" | "bot";
  content: string;
}

export default function Dashboard() {
  const { data: session, status } = useSession();
  const [messages, setMessages] = useState<Message[]>([
    {
      role: "bot",
      content: "Hello! I'm your medical assistant. How can I help you today?",
    },
  ]);
  const [inputMessage, setInputMessage] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  // If the user is not authenticated, redirect to login
  if (status === "unauthenticated") {
    redirect("/login");
  }

  // If the session is still loading, show a loading state
  if (status === "loading") {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <p className="text-lg text-gray-600">Loading...</p>
      </div>
    );
  }

  // Function to handle sending a message
  async function handleSendMessage(e: React.FormEvent) {
    e.preventDefault();
    
    if (!inputMessage.trim() || isLoading) return;

    const userMessage: Message = {
      role: "user",
      content: inputMessage,
    };

    // Add the user message to the chat
    setMessages((prev) => [...prev, userMessage]);
    setInputMessage("");
    setIsLoading(true);

    // In a real app, you would call your AI service here
    // This is a simple mock response
    setTimeout(() => {
      const botMessage: Message = {
        role: "bot",
        content: "This is a mock response. In a real application, this would be generated by an AI model based on your medical query.",
      };
      setMessages((prev) => [...prev, botMessage]);
      setIsLoading(false);
    }, 1000);
  }

  // Function to handle sign out
  async function handleSignOut() {
    await signOut({ redirect: true, callbackUrl: "/" });
  }

  return (
    <div className="flex min-h-screen flex-col bg-gray-50">
      {/* Header */}
      <header className="bg-white p-4 shadow">
        <div className="mx-auto flex max-w-6xl items-center justify-between">
          <h1 className="text-xl font-bold text-gray-800">Medical Chatbot</h1>
          <div className="flex items-center space-x-4">
            <span className="text-sm text-gray-600">
              Welcome, {session?.user?.name || "User"}
            </span>
            <button
              onClick={handleSignOut}
              className="rounded bg-gray-200 px-3 py-1 text-sm text-gray-700 hover:bg-gray-300"
            >
              Sign out
            </button>
          </div>
        </div>
      </header>

      {/* Main content */}
      <main className="mx-auto flex w-full max-w-4xl flex-1 flex-col p-4">
        {/* Chat messages */}
        <div className="mb-4 flex-1 overflow-y-auto rounded-lg border border-gray-200 bg-white p-4 shadow">
          <div className="space-y-4">
            {messages.map((message, index) => (
              <div
                key={index}
                className={`flex ${
                  message.role === "user" ? "justify-end" : "justify-start"
                }`}
              >
                <div
                  className={`max-w-[80%] rounded-lg px-4 py-2 ${
                    message.role === "user"
                      ? "bg-blue-500 text-white"
                      : "bg-gray-100 text-gray-800"
                  }`}
                >
                  <p>{message.content}</p>
                </div>
              </div>
            ))}
            {isLoading && (
              <div className="flex justify-start">
                <div className="max-w-[80%] rounded-lg bg-gray-100 px-4 py-2 text-gray-800">
                  <p>Thinking...</p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Chat input */}
        <form onSubmit={handleSendMessage} className="flex space-x-2">
          <input
            type="text"
            value={inputMessage}
            onChange={(e) => setInputMessage(e.target.value)}
            placeholder="Type your medical question..."
            className="flex-1 rounded-lg border border-gray-300 px-4 py-2 focus:border-blue-500 focus:outline-none"
            disabled={isLoading}
          />
          <button
            type="submit"
            className="rounded-lg bg-blue-500 px-4 py-2 font-medium text-white hover:bg-blue-600 disabled:bg-blue-300"
            disabled={isLoading || !inputMessage.trim()}
          >
            Send
          </button>
        </form>
      </main>
    </div>
  );
}
